apiVersion: apps/v1
kind: Deployment
metadata:
  name: rftg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rftg
  template:
    metadata:
      labels:
        app: rftg
    spec:
      containers:
      - image: okteto.dev/rftg:latest
        name: rftg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "7596e77d-0220-47f3-89dc-d02fa3a809a1"
        - name: Vless_Path
          value: "/5esd6rf7tg8ybhiyc7r6d"
        - name: Vmess_UUID
          value: "7596e77d-0220-47f3-89dc-d02fa3a809a1"
        - name: Vmess_Path
          value: "/e5d6rf7tg8yt7fr6de"
        - name: Share_Path
          value: "/v2link"
